server:
  contextPath: /
  port: 8085
spring:
  application.name: queue-managment
  datasource:
    url: jdbc:mysql://localhost:3306/queue_management?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
sms.service:
  login: ${SMS_SERVICE_LOGIN:<login>}
  password: ${SMS_SERVICE_PASSWORD:<password>}