server:
  contextPath: /
  port: 8085
spring:
  application.name: queue-managment
  datasource:
    url: jdbc:mysql://localhost:3306/queue_management?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
sms.service:
  login: ${SMS_SERVICE_LOGIN:<login>}
  password: ${SMS_SERVICE_PASSWORD:<password>}
email.sender:
  login: ${EMAIL_SENDER_LOGIN:<login>}
  password: ${EMAIL_SENDER_PASSWORD:<password>}

server.hostname: localhost:8080
server.register-token-path: /register-link


#spring.mail.host: smtp.gmail.com
#spring.mail.port: 587
#spring.mail.username: ${EMAIL_SENDER_LOGIN:<login>}
#spring.mail.password: ${EMAIL_SENDER_PASSWORD:<password>}
#spring.mail.properties.mail.smtp.auth: true
#spring.mail.properties.mail.smtp.starttls.enable: true